services:
  redis:
    image: redis:alpine
    restart: always

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./volumes/db/:/var/lib/postgresql/data/

  application:
    build: ./application/
    restart: always
    volumes:
      - ./volumes/app/storage/:/app/storage/
    command: "/bin/sh -c '
      python manage.py wait_for_redis &&
      python manage.py wait_for_db &&
      python manage.py makemigrations --noinput &&
      python manage.py migrate --noinput &&
      gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    '"
    env_file:
      - application/.env
    depends_on:
      - redis
      - db

  nginx:
    build: ./nginx/
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - application