services:
  redis:
    image: redis:alpine
    restart: always

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./volumes/db/:/var/lib/postgresql/data/

  application:
    build: ./application/
    restart: always
    volumes:
      - ./volumes/app/storage/:/app/storage/
    command: "/bin/sh -c '
      python manage.py wait_for_redis &&
      python manage.py wait_for_db &&
      python manage.py makemigrations --noinput &&
      python manage.py migrate --noinput &&
      gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    '"
    env_file:
      - application/.env
    depends_on:
      - redis
      - db

  nginx:
    build: ./nginx/
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./logs/nginx/:/var/log/nginx/  # Self
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf   # Self
      - ./volumes/certbot/www/:/vol/www/   # SSL
      - ./volumes/certbot/conf/:/etc/letsencrypt/   # SSL
    depends_on:
      - application

  certbot:
    image: certbot/dns-cloudflare
    container_name: certbot
    volumes:
      - ./volumes/certbot/www/:/vol/www/
      - ./volumes/certbot/conf/:/etc/letsencrypt/
      - ./nginx/cloudflare.ini:/etc/cloudflare/cloudflare.ini
    entrypoint: "/bin/sh -c 'if [ ! -f /etc/letsencrypt/live/dev-help.ir/fullchain.pem ]; then \
          echo \"No SSL found, requesting certificate...\"; \
          certbot certonly --dns-cloudflare --force-renewal --rsa-key-size 4096 --noninteractive \
          --dns-cloudflare-credentials /etc/cloudflare/cloudflare.ini --email ismryazdan@gmail.com \
          --agree-tos --no-eff-email -w /vol/www/ -d dev-help.ir --preferred-challenges dns-01; \
        else \
          cert_file_time=$(stat -c %Y /etc/letsencrypt/live/dev-help.ir/fullchain.pem); \
          current_time=$(date +%s); \
          time_diff=$(( (current_time - cert_file_time) / 86400 )); \
          if [ $$time_diff -ge 60 ]; then \
            echo \"Certificate is older than 60 days, renewing...\"; \
            certbot renew --dns-cloudflare --dns-cloudflare-credentials /etc/cloudflare/cloudflare.ini --quiet; \
          else \
            echo \"Certificate is still valid, no need to renew.\"; \
          fi; \
        fi;'"
